training:
    epochs: 25
    batches: 64
data:
    directory: data/
    train:
        x: data/01_trn_x.npy
        y: data/01_trn_y.npy
        c: data/01_trn_c.npy
        t: data/01_trn_t.npy
    test:
        x: data/01_trn_x.npy
        y: data/01_trn_y.npy
        c: data/01_trn_c.npy
        t: data/01_trn_t.npy
    validate:
        x: data/01_trn_x.npy
        y: data/01_trn_y.npy
        c: data/01_trn_c.npy
        t: data/01_trn_t.npy
    output_path: plots/
    weight_path: weights/
